name: Validate-Frontmatter-in-All-Rules

on:
  push:
    branches: [main]
    paths:
      - 'rules/**/rule.md' 
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate-all-frontmatter:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Find all Markdown files in rules
        run: |
          find rules -name '*.md' > all_rules_files.txt

      - name: Read file list and process
        id: file_list
        run: |
          FILE_LIST=$(cat all_rules_files.txt)
          echo "Found Markdown files:"
          echo "$FILE_LIST"
          echo "FILE_LIST<<EOF" >> $GITHUB_ENV
          echo "$FILE_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd scripts/frontmatter-validator
          npm install

      - name: Validate Frontmatter in Rule Files
        run: |
          cd scripts/frontmatter-validator
          for file in $FILE_LIST; do
            node frontmatter-validator.js "$file"
          done > validation_output.txt
          cat validation_output.txt >> $GITHUB_STEP_SUMMARY

      - name: Create Job Summary
        run: |
          echo "## Frontmatter Validation Results" >> $GITHUB_STEP_SUMMARY
          cat validation_output.txt >> $GITHUB_STEP_SUMMARY
